export const SAVE_MD5_ENCRYPTION_INPUT = 'SAVE_MD5_ENCRYPTION_INPUT';
export const SAVE_MD5_ENCRYPTION_RESULT = 'SAVE_MD5_ENCRYPTION_RESULT';
export const SAVE_TAB_POSITION = 'SAVE_TAB_POSITION';
export const SAVE_MD5_RECORD_TO_HISTORY = 'SAVE_MD5_RECORD_TO_HISTORY';
